### ISSUE TITLE
Implement the profile page.

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-spa#15]
### Tasks
- [x] Create a component showing the profile page header (picture and user name).
- [x] Create a component representing a profile section.
- [x] Create a component representing a profile property.
- [x] Build the profile page skeleton using the created component.
- [x] Load the user using the authService
- [x] Load the user objective using ResourceService
- [x] Handle the update of the objective property
- [x] Handle the delete click
- [x] Handle the export button
- [x] Handle the log out button

### Resources
![image](https://user-images.githubusercontent.com/31938998/96172064-1d51b500-0f26-11eb-9be1-94c957d03011.png)
