### ISSUE TITLE
The progress overview component should handle empty logbook

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-spa#21]
### Current behavior
The progress overview component doesn't handle an empty logbook.

### Objective
The component should show a 0% progress indicator and invite the user to start tracking.

### Tasks
- [x] Finish the component design on Figma
- [x] Update the React component to match the design
- [x] Handle the empty logbook
- [x] Handle data fetching by using the [skeleton material UI component](https://material-ui.com/components/skeleton/).
### Resources
![image](https://user-images.githubusercontent.com/31938998/95781802-dae26b00-0cce-11eb-94c2-12f995c4f7da.png)
![image](https://user-images.githubusercontent.com/31938998/95783062-58a77600-0cd1-11eb-9762-e9a35527406a.png)
