### ISSUE TITLE
Replace the navigation drawer with a bottom navigation

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-spa#22]
### Current behavior
Currently the application use a navigation drawer for navigation. It is useless as the first version of the app will only have 3 different main screen. The objective is to replace this drawer with a [bottom navigation component](https://material-ui.com/components/bottom-navigation/).

The resources section contains a screenshot showing what the home page should look like.

### Tasks
- [x] Create a React bottom navigation component (3 entries: home, history, and statistics).
- [x] Update the Page component: replace the navigation drawer with the bottom navigation component.
- [x] Edit the application bar component and remove the menu button
- [x] Delete the navigation drawer from the project
- [x] Implement the bottom navigation entry click handler

### Resources 
<p align="center" width="100px"><img src="https://user-images.githubusercontent.com/31938998/95778509-9227b380-0cc8-11eb-8e01-bfd09b06b3cb.png"/></p>
