### ISSUE TITLE
The user should be able to control its rides from the home page

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-spa#23]
### Objective
The objective is to implement the frontend and the data handling to allow a user to control rides in the home page.

The user should be able to:
- Start a ride
- Finish the current ride (commenting and giving feedback included)
- Cancel the current ride

### Tasks
- [x] Implement the basic component structure
- [x] Test the `RideControlCardAction` component
- [x] Test the `RideControlCardContent` component
- [x] Test the `RideControlCard` component
- [x] The card action buttons should be justified to the right
- [x] Add the component to the home page (it should be below the progress overview component).
- [x] Handle the data handling on the home page level

### Resources
![image](https://user-images.githubusercontent.com/31938998/95784173-a02f0180-0cd3-11eb-9410-97e8e7afe2ab.png)
![image](https://user-images.githubusercontent.com/31938998/95784228-bc32a300-0cd3-11eb-8b41-545126585f71.png)
