### ISSUE TITLE
The user should be able to see its profile using the application bar

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-spa#25]
### Expected behavior
- The application bar should contain an avatar (user profile picture)
- The avatar should redirect to the /profile route
- If the user has no profile picture then the avatar should the user initials

### Tasks
- [x] Include an [avatar component](https://material-ui.com/components/avatars/) in the application bar
- [x] Handle clicks on the avatar to redirect to the /profile route
- [x] The page component should have a special type of page without a bottom navigation
- [ ] Implement the skeleton of the profile page.

### Resources
![image](https://user-images.githubusercontent.com/31938998/96043381-27fd4300-0e6f-11eb-9a8e-530a4da62a58.png)
