### ISSUE TITLE
The user should see the most recent rides on the home page so that he can quickly access them.

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-spa#26]
### Expected behavior 
- The component shows the three most recent rides
- The rides are clickable: they redirect to the details page of the entry
- When the user has no rides, a suited message is shown

### Tasks
- [x] Create a component that represents one ride overview (redirects to the ride details on click)
- [x] Create a component that contain the entries
- [x] Add the component to the home page

### Resources
![image](https://user-images.githubusercontent.com/31938998/96045610-7c55f200-0e72-11eb-967d-4cf9b1750668.png)
