### ISSUE TITLE
The localtion field should be able to select and create locations.

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-spa#65]
### Tasks
- [x] Create the location service
- [x] Implement the post method in the HttpService class
- [x] Implement the create method in the LocationService class
- [x] Implement the getAll method in the LocationService class
- [x] Update the location field to support location creation
- [x] Update the location field to load and show locations from the back-end
- [x] The field should return a location id.
- [x] The field should take in a default location id (one of the loaded locations) so that it can show it by default.
