### ISSUE TITLE
The stop form should update a stop after submission.

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-spa#66]
### A bit of context
The stop form is intended to be used by a ride form. The ride form does not update a ride stop id of its entity. What happens is that the stop related to the ride will get its data edited. The form just need to update the backend data.

The stop form should be able to read a location id from the location field.

### Tasks
- [x] The ride form should be able to read the departure and arrival id.
- [x] A location id should be passed instead of an entity in the location field
- [x] After submission a put request should be sent to the backend
- [x] Any conflict or error should be handled be redirecting to the error page
