### ISSUE TITLE
Home page overview card API request.

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-spa#74]
### Description
The home page overview card should show the current user objective overview, not the static data from the JSON sample data.

### Tasks
- [x] Fetch the current driver data from the API in the `DriverService.getCurrentDriver` function.
- [x] Fetch the driver statistics data from the API in the `DriverService.getCurrentDriver` function.
- [x] In the `ProgressOverviewCard.useEffect` call the `DriverService.getCurrentDriver` and load the data into the state.
