### ISSUE TITLE
Rides pagination

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-spa#75]
### Expected behavior
The history tab should have a *Load more* button. The button should be at the end of the rides list page. When the user clicks it, a new page is fetched and appended to the list. The button should be hidden when the user reaches the last page.

### Tasks
- [x] Adapt the `RideService.getAll` function to read `totalPages`, `isLastPage`, and `rides`.
- [x] Handle pagination in the `RideService.getAll` function.
- [x] Add the *Load more* button at the end of the rides list.
- [x] Fetch a new page of rides when the button is clicked
- [x] Check for the last page and hide the button when it is reached
