### ISSUE TITLE
Traffic condition unknown value

### ISSUE THREAD

**Issue by lfarci** [Lofaloa/journal-de-bord-spa#79]
### Description
It is possible that a ride has an invalid value for the traffic condition field. This happens when the back-end messes up the field. The value should be checked when loading data end marked as unknown. If a value is out of range then it should be treated as unknown, not undefined (which causes an error). An unknown value should not be shown in the ride details page.

### Tasks
- [ ] Create the `TrafficCondition.Unknown`.
- [ ] Update the `RideService` to replace the invalid values by `TrafficCondition.Unknown`.
- [ ] Handle the new value in the traffic condition utility functions.
- [ ] Hide the traffic condition field when the value is set to unknown.

### Resources
Here is a warning shown when opening the edit page of an invalid ride.
![traffic_condition_warning](https://user-images.githubusercontent.com/31938998/113216350-859a1600-927c-11eb-8500-6e82e6b393a7.png)

Here is a screenshot of an invalid ride details page. The traffic field is left blank.
![image](https://user-images.githubusercontent.com/31938998/113216448-aa8e8900-927c-11eb-9541-0c75bce88bbe.png)
