### ISSUE TITLE
Refactor the services

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-spa#81]
### Description
The services can be found in the `services` folder. A service is responsible for providing the application data. The structure was not thought out during the beginning of the project. They should be refactored.

### Tasks
- [ ] The `ResourceService` class references should be removed and the class be deleted.
- [ ] Create a `services/api` folder that contain all the backend services.
- [ ] Create a `services/api/index.ts` that export the different services.
- [ ] Create a `services/authentication that contain the authentication logic.
