### ISSUE TITLE
Home page recent rides data

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-spa#82]
### Description
The recent rides card component should load the component data from the back-end.

### Tasks
- [x] Move the call to the API in the `RecentRidesCard`.
- [x] Call the `RideService.getAll` with the page `0` and size to `5`.
- [x] The loaded rides should be converted to `RecentRide preview` in the `RideService.getAllPreviews` function.
- [x] Load the recent rides into the component state.
- [x] Test the component
