### ISSUE TITLE
Start ride form dialog

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-spa#83]
### Description
The dialog should be handled in the `RideControlCard`. It is shown when a user wants to start a new ride. When submitted, it should initialize a ride resource in the back-end.

### Tasks
- [x] Move the `StartRideFormDialog` from `Home` to `RideControlCard`.
- [x] Fix this [issue](https://github.com/Lofaloa/journal-de-bord-rest-api/issues/40) of the REST API.
- [X] Create a call to the back-end that sends the initialized ride data over.
- [x] Make sure the location field is using the current location for the departure.
- [x] Create a new component: `FormDialog`. It should handle the loading and error state for a `Dialog`.
- [x] Write unit tests
- [x] I should be able to create a location using the location field and start tracking from my position.
